#!/bin/sh
unset IFS
set -euf

BUCKET='s3://octane'
VERSION="$(octane --version)"
DEST="$BUCKET/octane-$VERSION/"
ARTIFACTS='.rockhopper/artifacts'

# Accelerate connection timeouts
# Reduce console noise
aws() {
    command aws \
        --cli-connect-timeout 1 \
        "$@" \
        >/dev/null
}

aws s3 cp --recursive "$ARTIFACTS" "$DEST"
echo "install media uploaded to \"$DEST\""
