---
name: "Test"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Test:
    runs-on: "ubuntu-24.04"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-go@v5"
      with:
        go-version: "1.25.3"
    - name: "provision native dependencies"
      run: |
        sudo apt update
        sudo apt install -y libasound2-dev
    - run: "go test"
